Gui set geometry
SABS-R3-projects/PKPD pull request #17
Opened 2019-11-27 11:17 UTC by Rebecca-Rumney

Set Geometry function is now functional. Informally tested by just building the window and seeing whether it worked.

2019-11-27 11:19 UTC, Rebecca-Rumney commented
I also changed the __init__ of the class to have some variables required by the function

2019-11-27 16:11 UTC, simonmarchant commented
Everything looks good to me Rebecca! Obviously we probably don't want the under-construction stuff once it gets to master but that's not yet. If you merge in the setup.py then it'll pass the travis tests, which we may as well get before merging.

2019-11-27 16:17 UTC, barnums reviewed
All looks good to me!

2019-11-27 16:20 UTC, DavAug requested changes

2019-11-27 16:20 UTC, DavAug commented on PKPD/gui/abstractGui.py
abc is no longer necessary. Please remove

2019-11-27 16:20 UTC, DavAug commented on PKPD/gui/mainWindow.py
> +
testing separate from class

2019-11-27 16:20 UTC, DavAug commented on PKPD/gui/mainWindow.py
> +        self.showMaximized()
show probably also better not automatically executed within a test

2019-11-27 16:20 UTC, DavAug commented on PKPD/gui/mainWindow.py
> +        self.showMaximized()
would make automated testing with travis difficult

2019-12-12 10:37 UTC, simonmarchant commented
All changes from set geometry are incorporated into #22 so closing this.

2019-12-12 10:37 UTC, closed without merging