labels sliders with label & units
SABS-R3-projects/PKPD pull request #47
Opened 2020-01-29 15:45 UTC by simonmarchant

Simple addition of a function. Please could at least one person see if it's ok.

2020-02-05 10:44 UTC, DavAug requested changes
There is some stuff that has been introduced in the model repository branch. As I currently work on that branch, just ignore it and don't merge into the master just yet.

2020-02-05 10:44 UTC, DavAug commented on PKPD/gui/mainWindow.py
> +import myokit
please move import Myokit to the top, i.e.

import myokit

from PKPD.....

2020-02-05 10:44 UTC, DavAug commented on PKPD/gui/mainWindow.py
> +            #Check Units in MMT file
to be consistent through out the program: space between # and comment, i.e.

`# check units in mmt file`

2020-02-05 10:44 UTC, DavAug commented on PKPD/gui/mainWindow.py
> +            except Exception as e: #Display Warning if Inconsistent
same here

2020-02-05 10:44 UTC, DavAug commented on PKPD/gui/mainWindow.py
> +
remove empty lines here, i.e. line 186 and 187

2020-02-05 10:44 UTC, DavAug commented on PKPD/gui/mainWindow.py
> +
remove empty line 204. Functions/ methods are separated by 2 empty lines.

2020-02-12 15:30 UTC, DavAug approved these changes

2020-02-12 15:31 UTC, simonmarchant commented
All approved and tests passing, merging now.

2020-02-12 15:31 UTC, merged